### ISSUE TITLE
Cannot Add Person in the Data People page

### ISSUE THREAD

**Issue by Hesketh** [Hesketh/MecatolArchives#10]
The add button on the person page does not function. Making it impossible to add players.

Investigation of the containers logs indicate its a null ref in Get Initials
```
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Hesketh.MecatolArchives.API.Data.Person.get_Initials() in D:\a\MecatolArchives\MecatolArchives\API.Data\Person.cs:line 15
         at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
         at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
         at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Serialize(Utf8JsonWriter writer, T& rootValue, Object rootValueBoxed)
         at System.Text.Json.JsonSerializer.WriteString[TValue](TValue& value, JsonTypeInfo`1 jsonTypeInfo)
         at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
         at MudBlazor.MudDataGrid`1.SetEditingItemAsync(T item)
         at Hesketh.MecatolArchives.Website.Components.Pages.Data.PeoplePage.CreateNew() in D:\a\MecatolArchives\MecatolArchives\Website\Components\Pages\Data\PeoplePage.razor:line 67
         at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
         at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.PostAsync[TState](Task antecedent, Action`1 callback, TState stat
```

**Comment by Hesketh** [comment]
Issue resolved. Null Name (a state only found on construction) will return empty initials
